FROM almalinux:9
ENV course="Devops with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"
# here username is key , some_user is default value
ARG USERNAME=sivakumar    
RUN echo "Hello User: ${USERNAME}" 
CMD ["sleep", "100"]        